User session update
profcomff/auth-api pull request #109
Opened 2023-05-07 19:10 UTC by Temmmmmo

1. Были добавлены поля create_ts и update_ts к пользователям, группам, методам аутентификации и пользовательским сессиям.
2. Добавлены поля имени и последней активности пользовательской сессии.
3. Доработаны ручки в пользовательских сессиях. Теперь при создании сессии можно присвоить ей имя. Также при возврате данной сессии или всех сразу в ответе будет поле с именем соответствующей сессии.

2023-05-08 16:07 UTC, dyakovri commented on auth_backend/models/db.py
> +    update_ts: Mapped[datetime.datetime] = mapped_column(DateTime, default=datetime.datetime.utcnow)
Тут не хватает автоматического изменения при изменениях модели
Пример: https://github.com/profcomff/timetable-api/blob/main/calendar_backend/models/db.py#L26-L28

2023-05-08 16:08 UTC, dyakovri commented on auth_backend/models/db.py
> +    update_ts: Mapped[datetime.datetime] = mapped_column(DateTime, default=datetime.datetime.utcnow)
Ну и во всех остальных так же

2023-05-08 16:11 UTC, dyakovri commented on auth_backend/routes/user_session.py
> +        )
А зачем это делать в 2 разные ветки? Просто передаешь имя сессии, и если оно None – значит выставляется None

2023-05-08 16:12 UTC, dyakovri commented on auth_backend/utils/user_session_control.py
> +    session_name: str = '',
Перенеси его последним перед звездочкой. Тогда параметр можно будет задавать через запятую неименованно

2023-05-08 16:12 UTC, dyakovri commented on auth_backend/utils/user_session_control.py
> +    session_name: str = '',
Лучше как дефолт сделать None

2023-05-08 16:13 UTC, dyakovri commented on auth_backend/utils/user_session_control.py
> +        last_activity=datetime.utcnow(),
Это значение и так поставится по умолчанию при создании сессии. Ты это указал в настройках модели (параметр у `mapped_column`).

2023-05-08 22:35 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +            result.update(dict(session_scopes=[_scope.name for _scope in session.scopes]))
а почему не `result["session_scopes"]=[_scope.name for _scope in session.scopes]`

2023-05-08 22:59 UTC, grigoriev-semyon requested changes
упадет на миграциях

2023-05-09 12:56 UTC, grigoriev-semyon approved these changes

2023-05-09 12:56 UTC, merged