User session patch
profcomff/auth-api pull request #144
Opened 2023-07-26 19:06 UTC by Temmmmmo

## Изменения
Добавлена возможность изменять права и имя определенной сессии пользователя.

## Реализации
Добавлена ручка патча в пользовательской сессии.

## Детали
Отныне, чтобы добавить какие-либо скоупы или поменять название нужной сессии, не нужно создавать новую.

## Check-List
- [x] Вы проверили свой код перед отправкой запроса?
- [x] Вы написали тесты к реализованным функциям?
- [x] Вы не забыли применить black и isort?

2023-07-26 19:11 UTC, Temmmmmo commented on auth_backend/exceptions.py
> +    def __init__(self, obj: type, obj_id_or_name: int | str):
В принципе это можно было не делать

2023-07-26 19:28 UTC, grigoriev-semyon requested changes

2023-07-26 19:28 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +    update_session.scopes = list(scope for scope in scopes)
list(scopes)

2023-07-26 19:28 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +    db.session.commit()
Там автокоммит стоит

2023-07-26 19:28 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +        update_session.id, session=db.session, **session_update_info.model_dump(exclude_unset=True, exclude='scopes')
Разве в exclude надо не set?

2023-07-26 19:28 UTC, grigoriev-semyon commented on auth_backend/schemas/models.py
> +SessionUpdate.model_rebuild()
По моему ее не надо ребилдить тут

2023-07-26 19:34 UTC, Temmmmmo commented on auth_backend/routes/user_session.py
> +    update_session.scopes = list(scope for scope in scopes)
Я побоялся почему-то так писать)))

2023-07-26 19:34 UTC, Temmmmmo commented on auth_backend/routes/user_session.py
> +    update_session.scopes = list(scope for scope in scopes)
Исправил

2023-07-26 19:34 UTC, Temmmmmo commented on auth_backend/routes/user_session.py
> +    db.session.commit()
Да?
Исправил

2023-07-26 19:35 UTC, Temmmmmo commented on auth_backend/routes/user_session.py
> +        update_session.id, session=db.session, **session_update_info.model_dump(exclude_unset=True, exclude='scopes')
В смысле? 
Тут мы скоупы исключаем, потому что там проблема с тем, что к типу Scope какой-то там метод не применим.

2023-07-26 19:36 UTC, Temmmmmo commented on auth_backend/schemas/models.py
> +SessionUpdate.model_rebuild()
Тут я методом угадывания это написал. Как понять: надо или не надо ребилдить?

2023-07-26 19:45 UTC, Wudext reviewed
Ну если работает то жить можно

2023-07-26 19:45 UTC, Wudext commented on auth_backend/routes/user_session.py
> +    if update_session is None:
if not update_session

2023-07-26 19:48 UTC, Temmmmmo commented on auth_backend/routes/user_session.py
> +    if update_session is None:
https://pythonworld.ru/tipy-dannyx-v-python/none.html#:~:text=Python%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D1%82%20%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D0%BF%D0%B5%D1%80%D0%B5%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2,%2C%20%D0%BD%D0%B0%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%2C%20MyObject%20%3D%3D%20MyOtherObject.&text=%D0%98%D0%BD%D1%82%D0%B5%D1%80%D0%B5%D1%81%D0%BD%D0%BE%2C%20%D0%BD%D0%B5%20%D0%BF%D1%80%D0%B0%D0%B2%D0%B4%D0%B0%20%D0%BB%D0%B8%3F,%D1%81%20%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E%20%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%B2%D0%BE%D0%B3%D0%BE%20%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%20is.

2023-07-26 19:49 UTC, Temmmmmo commented on auth_backend/routes/user_session.py
> +    if update_session is None:
По идее и по-твоему можно, но не уверен...
Лучше так оставить

2023-07-26 21:49 UTC, grigoriev-semyon commented on auth_backend/schemas/models.py
> +SessionUpdate.model_rebuild()
если в модели использованы для типов ссылки на нижепрописанные объекты

2023-07-26 21:51 UTC, Temmmmmo commented on auth_backend/routes/user_session.py
> +        update_session.id, session=db.session, **session_update_info.model_dump(exclude_unset=True, exclude='scopes')
исправил

2023-07-26 21:52 UTC, Temmmmmo commented on auth_backend/routes/user_session.py
> +    if update_session is None:
оставил так

2023-07-26 21:55 UTC, Temmmmmo commented on auth_backend/schemas/models.py
> +SessionUpdate.model_rebuild()
тогда реально не надо

2023-07-26 21:55 UTC, Temmmmmo commented on auth_backend/schemas/models.py
> +SessionUpdate.model_rebuild()
исправил

2023-07-26 22:00 UTC, grigoriev-semyon commented on auth_backend/schemas/models.py
> +class SessionUpdate(Base):
SessionPatch

2023-07-26 22:07 UTC, Temmmmmo commented on auth_backend/schemas/models.py
> +class SessionUpdate(Base):
Исправил

2023-07-28 13:48 UTC, grigoriev-semyon approved these changes

2023-07-28 13:49 UTC, merged