email reset fixes
profcomff/auth-api pull request #155
Opened 2023-08-07 01:47 UTC by grigoriev-semyon

## Изменения
Выпилил требования мыла в подтверждении ресета пароля, пофиксил множественный запрос ресета почты

## Check-List
- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить black и isort?

***P.S. Проставьте x в квадратные скобки в нужных пунктах. Example: [x]***

2023-08-07 17:24 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +            if (attr := getattr(self, k)) and getattr(attr, "is_deleted") != True:
!= True, серьезно?

2023-08-07 17:24 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +            if (attr := getattr(self, k)) and getattr(attr, "is_deleted") != True:
Ну хотя бы is not

2023-08-07 17:24 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +    new_password: constr(min_length=1) | None = None
Они же все не Nullable были, не? Почему сейчас можно None?

2023-08-07 17:24 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +    email: constr(min_length=1) | None = None
Давай тут избавимся от мыла, оно же не нужно

2023-08-07 17:24 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        Передать надо либо email, либо сессию + новый пароль + старый пароль
Странная ручка

2023-08-07 17:24 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        Передать надо либо email, либо сессию + новый пароль + старый пароль
Почему это не 2 разных?

2023-08-07 17:25 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        Передать надо либо email, либо сессию + новый пароль + старый пароль
потому что изначально так было))

2023-08-07 17:25 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +    email: constr(min_length=1) | None = None
почему не нужно
а если ты забыл пароль?

2023-08-07 17:26 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +    new_password: constr(min_length=1) | None = None
пароли были нуллабл
потому что там валидатор написан

2023-08-07 17:26 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/auth_method.py
> +            if (attr := getattr(self, k)) and getattr(attr, "is_deleted") != True:
поправлю

2023-08-07 18:03 UTC, Wudext requested changes
Я так понял что в новой логике вместо мыла нужен старый пароль и новый пароль. А если человек старый пароль забыл, то мыло все-равно нужно. В чем тогда смысл ишью?

2023-08-20 10:42 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        Передать надо либо email, либо сессию + новый пароль + старый пароль
разделил ручки

2023-08-25 12:57 UTC, grigoriev-semyon commented
@Temmmmmo

2023-08-25 23:37 UTC, Temmmmmo approved these changes

2023-08-25 23:37 UTC, merged