Oauth kafka
profcomff/auth-api pull request #156
Opened 2023-08-09 01:06 UTC by Temmmmmo

## Изменения
Были добавлены методы получения информации о пользователе и ее дальнейшая инициализация.

## Реализации
В каждом _OAuth-классе_ реализован метод для парсинга основной информации, которую можно получить при аутентификации пользователя через данный _OAuth-метод_.

## Детали
При аутентификации пользователя создается `BackgroundTask`, который отправляет собранную о пользователе информацию в [`userdata-api`](https://github.com/profcomff/userdata-api), используя уже реализованную **Apache Kafka**.

## Check-List
- [x] Вы проверили свой код перед отправкой запроса?
- [x] Вы написали тесты к реализованным функциям? - **not required** 
- [x] Вы не забыли применить black и isort?

2023-08-09 01:35 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +from ..kafka.kafka import producer
резолв неправильный

2023-08-09 01:35 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +    _source = "email"
резолв неправильный

2023-08-09 01:35 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/github.py
> +from ..kafka.kafka import producer
резолв неправильный

2023-08-09 01:35 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/github.py
> +    _source = 'github'
убери сурсы я от них отказался

2023-08-09 01:36 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +    _source = 'google'
убери сурсы я от них отказался

2023-08-09 01:36 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +    _source = 'lk-msu'
убери сурсы я от них отказался

2023-08-09 01:36 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/telegram.py
> +    _source = 'telegram'
убери сурсы я от них отказался

2023-08-09 01:36 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/vk.py
> +from ..kafka.kafka import producer
абсолютный иморт давай во всех таких местах

2023-08-09 01:37 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/vk.py
> +    _source = "vk"
убери сурсы я от них отказался

2023-08-09 01:37 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/vk.py
> +        userdata = VkAuth()._convert_data_to_userdata_format(userinfo['response'][0])
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:37 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/vk.py
> +        userdata = VkAuth()._convert_data_to_userdata_format(userinfo['response'][0])
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:38 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +        userdata = YandexAuth()._convert_data_to_userdata_format(userinfo)
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:38 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +        userdata = YandexAuth()._convert_data_to_userdata_format(userinfo)
то есть у тебя тут три варианта 
выбери один

2023-08-09 01:38 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +        userdata = YandexAuth()._convert_data_to_userdata_format(userinfo)
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:38 UTC, grigoriev-semyon commented on auth_backend/kafka/kafka.py
> -
куда делось?

2023-08-09 01:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +            items.append({"category": "Личная информация", "param": "Пол", "value": data.get("sex")})
может основная информация?

2023-08-09 01:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +        if data.get("default_phone") and data.get("default_phone").get("number"):
много почт не надо

2023-08-09 01:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +from ..kafka.kafka import producer
абсолютный импорт давай как в мейне

2023-08-09 01:40 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +from ..kafka.kafka import producer
абсолютный импорт давай как в мейне

2023-08-09 01:40 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +from ..kafka.kafka import producer
абсолютный импорт давай как в мейне

2023-08-09 01:40 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/github.py
> +from ..kafka.kafka import producer
абсолютный импорт давай как в мейне

2023-08-09 01:41 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/telegram.py
> +            items.append({"category": "Личная информация", "param": "Фамилия", "value": data.get("last_name")})
основная лучше мб

2023-08-09 01:41 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/telegram.py
> +            items.append({"category": "Личная информация", "param": "Telegram", "value": data.get("username")})
это не юзердата и здесь я думаю не надо 
да @dyakovri ?

2023-08-09 01:41 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/telegram.py
> +            items.append({"category": "Личная информация", "param": "Фото", "value": data.get("photo_url")})
а мы сможем эту фотку получить по урлу?

2023-08-09 01:42 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/telegram.py
> +        userdata = TelegramAuth()._convert_data_to_userdata_format(userinfo)
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:42 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/telegram.py
> +        userdata = TelegramAuth()._convert_data_to_userdata_format(userinfo)
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:43 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +            items.append({"category": "Личная информация", "param": "Должность", "value": data.get("userType")['name']})
должность мне кажется это не личная инфа

2023-08-09 01:43 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +            items.append({"category": "Личная информация", "param": "Должность", "value": data.get("userType")['name']})
а если ``data.get("userType")==None`` то что?

2023-08-09 01:44 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +            student = data.get('student')
самое место для моржа

2023-08-09 01:44 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                    )
а почему нулевую берем?

2023-08-09 01:45 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                if entrants.get('faculty') != [] and entrants.get('faculty')['name']:
упадет если не передан факультет

2023-08-09 01:45 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                            "value": entrants.get('educationType')['name'],
упадет если нет ключа educationType

2023-08-09 01:46 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                if entrants.get("educationForm") != [] and entrants.get("educationForm")["name"]:
упадет если нет ключа educationType

2023-08-09 01:46 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                if entrants.get("groups") != [] and entrants.get("groups")[0]["name"]:
упадет если нет ключа educationType

2023-08-09 01:46 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                            "value": entrants.get("groups")[0]["name"],
упадет если нет ключа educationType

2023-08-09 01:46 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                entrants: dict[str | Any] = student.get("entrants")[0]
точно хинт тут нужен?

2023-08-09 01:47 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +        userdata = LkmsuAuth()._convert_data_to_userdata_format(userinfo)
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:47 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +        userdata = LkmsuAuth()._convert_data_to_userdata_format(userinfo)
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:48 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +        if data.get("picture"):
а по отдельности фио там нет?

2023-08-09 01:48 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +            items.append({"category": "Личная информация", "param": "Фото", "value": data.get("picture")})
мы эту фотку получим?

2023-08-09 01:48 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth()._convert_data_to_userdata_format(userinfo)
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:50 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/github.py
> +            items.append({"category": "Личная информация", "param": "GitHub", "value": data.get("url")})
ну наверное можно оставить вай нот

2023-08-09 01:51 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/github.py
> +        userdata = GithubAuth()._convert_data_to_userdata_format(userinfo)
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:51 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/github.py
> +        userdata = GithubAuth()._convert_data_to_userdata_format(userinfo)
он же был статик с cls а тут он вообще метод инстанса

2023-08-09 01:51 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +from ..kafka.kafka import producer
импорт в этом месте надо абсолютный

2023-08-09 12:23 UTC, Temmmmmo commented on Makefile
> +db-up:
исправил

2023-08-09 12:27 UTC, Temmmmmo commented on auth_backend/auth_plugins/email.py
> +from ..kafka.kafka import producer
исправил

2023-08-09 12:33 UTC, Temmmmmo commented on auth_backend/auth_plugins/email.py
> +    _source = "email"
исправил

2023-08-09 12:41 UTC, Temmmmmo commented on auth_backend/auth_plugins/github.py
> +from ..kafka.kafka import producer
исправил

2023-08-09 12:42 UTC, Temmmmmo commented on auth_backend/auth_plugins/github.py
> +    _source = 'github'
исправил

2023-08-09 12:43 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +    _source = 'google'
убрал

2023-08-09 12:48 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +    _source = 'lk-msu'
+

2023-08-09 12:48 UTC, Temmmmmo commented on auth_backend/auth_plugins/telegram.py
> +    _source = 'telegram'
+

2023-08-09 12:48 UTC, Temmmmmo commented on auth_backend/auth_plugins/vk.py
> +from ..kafka.kafka import producer
+

2023-08-09 12:49 UTC, Temmmmmo commented on auth_backend/auth_plugins/vk.py
> +    _source = "vk"
+

2023-08-09 12:51 UTC, Temmmmmo commented on auth_backend/auth_plugins/vk.py
> +        userdata = VkAuth()._convert_data_to_userdata_format(userinfo['response'][0])
+

2023-08-09 12:51 UTC, Temmmmmo commented on auth_backend/auth_plugins/yandex.py
> +        userdata = YandexAuth()._convert_data_to_userdata_format(userinfo)
+

2023-08-09 12:54 UTC, Temmmmmo commented on auth_backend/kafka/kafka.py
> -
магия
исправил

2023-08-09 12:56 UTC, Temmmmmo commented on auth_backend/auth_plugins/yandex.py
> +        if data.get("default_phone") and data.get("default_phone").get("number"):
ok

2023-08-09 12:57 UTC, Temmmmmo commented on auth_backend/auth_plugins/yandex.py
> +from ..kafka.kafka import producer
+

2023-08-09 12:57 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +from ..kafka.kafka import producer
+

2023-08-09 12:58 UTC, Temmmmmo commented on auth_backend/auth_plugins/telegram.py
> +            items.append({"category": "Личная информация", "param": "Telegram", "value": data.get("username")})
хз

2023-08-09 12:59 UTC, Temmmmmo commented on auth_backend/auth_plugins/telegram.py
> +            items.append({"category": "Личная информация", "param": "Фото", "value": data.get("photo_url")})
хороший вопрос

2023-08-09 12:59 UTC, Temmmmmo commented on auth_backend/auth_plugins/telegram.py
> +        userdata = TelegramAuth()._convert_data_to_userdata_format(userinfo)
+

2023-08-09 12:59 UTC, Temmmmmo commented on auth_backend/auth_plugins/telegram.py
> +        userdata = TelegramAuth()._convert_data_to_userdata_format(userinfo)
+

2023-08-09 13:06 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +            items.append({"category": "Личная информация", "param": "Должность", "value": data.get("userType")['name']})
Ну так, не зайдет же даже туда

2023-08-09 13:10 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +            items.append({"category": "Личная информация", "param": "Должность", "value": data.get("userType")['name']})
`data = {'a': None}
if data.get('a'):
    print('Hello, world!')`
`>> ...`

2023-08-09 13:19 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                    )
Можно цикл

2023-08-09 13:23 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                if entrants.get('faculty') != [] and entrants.get('faculty')['name']:
+

2023-08-09 13:23 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                            "value": entrants.get('educationType')['name'],
+

2023-08-09 13:23 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                if entrants.get("educationForm") != [] and entrants.get("educationForm")["name"]:
+

2023-08-09 13:24 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                            "value": entrants.get("groups")[0]["name"],
+

2023-08-09 13:24 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        if data.get("picture"):
Нет, там имени даже может не быть, там вполне ник может оказаться

2023-08-09 13:25 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +            items.append({"category": "Личная информация", "param": "Фото", "value": data.get("picture")})
Хз

2023-08-09 13:25 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth()._convert_data_to_userdata_format(guser_id)
+

2023-08-09 13:25 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth()._convert_data_to_userdata_format(userinfo)
+

2023-08-09 13:25 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth()._convert_data_to_userdata_format(userinfo)
+

2023-08-09 13:29 UTC, Temmmmmo commented on auth_backend/auth_plugins/github.py
> +        userdata = GithubAuth()._convert_data_to_userdata_format(userinfo)
+

2023-08-09 13:29 UTC, Temmmmmo commented on auth_backend/auth_plugins/github.py
> +        userdata = GithubAuth()._convert_data_to_userdata_format(userinfo)
+

2023-08-09 13:29 UTC, Temmmmmo commented on auth_backend/auth_plugins/github.py
> +            items.append({"category": "Личная информация", "param": "GitHub", "value": data.get("url")})
согл

2023-08-09 13:29 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth()._convert_data_to_userdata_format(userinfo)
+

2023-08-09 13:29 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth()._convert_data_to_userdata_format(userinfo)
+

2023-08-09 16:24 UTC, dyakovri commented on auth_backend/auth_plugins/github.py
> +        )
У меня много вопросов к @grigoriev-semyon 
1. Почему это надо задавать вручную, а оно не запускается само
2. Почему ты передаешь бгтаскс в кафку, а не кафку в бгтаскс, это же нелогично

2023-08-09 16:40 UTC, dyakovri commented on auth_backend/auth_plugins/github.py
> +        if data.get("url"):
Чем плохо, что мы заполним в value значение "None"
Эта проверка на наличие везде какая-то не оч актуальная

2023-08-09 16:40 UTC, dyakovri commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth._convert_data_to_userdata_format(userinfo)
А гугловая либа не умеет это делать одним запросом сама?

2023-08-09 16:40 UTC, dyakovri commented on auth_backend/auth_plugins/lkmsu.py
> +                            {"category": "Учёба", "param": "Номер зачётной книжки", "value": entrant.get("record_book")}
Это то же самое, что номер студенческого

2023-08-09 16:40 UTC, dyakovri commented on auth_backend/auth_plugins/vk.py
> +            items.append({"category": "Личная информация", "param": "VK-ID", "value": data.get("nickname")})
Может таки в "Контакты"?

2023-08-09 16:40 UTC, dyakovri commented on auth_backend/auth_plugins/yandex.py
> +            items.append({"category": "Личная информация", "param": "Пол", "value": data.get("sex")})
Тут будет "мужской"/"женский" маленькими буквами, чтоб было так же, как в ВК?

2023-08-09 16:40 UTC, dyakovri commented on auth_backend/auth_plugins/vk.py
> +                    items.append({"category": "Личная информация", "param": "Пол", "value": ""})
Или value = None?

2023-08-09 16:40 UTC, dyakovri commented on auth_backend/auth_plugins/vk.py
> +                case 0:
Ой бля, а давай ка через if. Иначе мы тут огребем в один прекрасный момент

2023-08-09 16:43 UTC, Temmmmmo commented on auth_backend/auth_plugins/vk.py
> +            items.append({"category": "Контакты", "param": "Родной город", "value": data.get("home_town")})
Родной город

2023-08-10 12:09 UTC, Temmmmmo commented on auth_backend/auth_plugins/telegram.py
> +            items.append({"category": "Личная информация", "param": "Telegram", "value": data.get("username")})
сделал

2023-08-10 12:10 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +            items.append({"category": "Личная информация", "param": "Должность", "value": data.get("userType")['name']})
сделал

2023-08-10 12:14 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        if data.get("picture"):
Да, Ром, тут обработать больно. Так как может быть ФИО там, которое обрабатывается легко, а может быть просто ник, который вбил пользователь.

2023-08-10 12:14 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +            items.append({"category": "Личная информация", "param": "Фото", "value": data.get("picture")})
Получим

2023-08-10 12:21 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                            {"category": "Учёба", "param": "Номер зачётной книжки", "value": entrant.get("record_book")}
да

2023-08-10 12:21 UTC, Temmmmmo commented on auth_backend/auth_plugins/vk.py
> +            items.append({"category": "Личная информация", "param": "VK-ID", "value": data.get("nickname")})
сделал

2023-08-10 12:23 UTC, Temmmmmo commented on auth_backend/auth_plugins/vk.py
> +                case 0:
сделал

2023-08-10 12:23 UTC, Temmmmmo commented on auth_backend/auth_plugins/vk.py
> +        if data.get("career") != [] and data.get("career")["city_name"]:
гениально, правда?))))

2023-08-10 12:34 UTC, Temmmmmo commented on auth_backend/auth_plugins/yandex.py
> +            items.append({"category": "Личная информация", "param": "Пол", "value": data.get("sex")})
male/female будет
Я сделал, чтобы так же, как и в вк было

2023-08-10 14:24 UTC, grigoriev-semyon requested changes
выпили проверки на None тогда как Рома сказал https://github.com/profcomff/auth-api/pull/156#discussion_r1288861620
И перенеси бг таски на уровень ручки пж те вынеси их из produce

2023-08-12 05:39 UTC, grigoriev-semyon requested changes
Обрати внимание что в юзердату из одного источника на один параметр можно записать только одно значение
Также комменты про гуглолибу посмотри
Ну и там по мелочи

2023-08-12 05:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                for entrant in student.get('entrants'):
а если там пустой массив то он же норм пропустит for
зачем лишний if?

2023-08-12 05:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                    if entrant.get("educationForm") and entrant.get("educationForm").get("name"):
юзердата не может воспринять несколько значений на один параметр из одного источника

2023-08-12 05:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/vk.py
> +            items.append({"category": "Карьера", "param": "Место работы", "value": data.get("career")["company"]})
если там список то как ты его собрался отправлять?
юзердата воспринимает строку только

2023-08-12 05:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +        if data.get("default_phone") and data.get("default_phone").get("number"):
вроде же договорились убрать ифы

2023-08-12 05:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +            cls.settings.KAFKA_USER_LOGIN_TOPIC_NAME,
присоединяюсь к вопросу Ромы
почему не сделать это средствами либы?

2023-08-12 05:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth._convert_data_to_userdata_format(userinfo)
присоединяюсь к вопросу Ромы
почему не сделать это средствами либы?

2023-08-13 13:57 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                for entrant in student.get('entrants'):
а, да

2023-08-13 13:58 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                    if entrant.get("educationForm") and entrant.get("educationForm").get("name"):
А где здесь значения на один параметр?

2023-08-13 14:09 UTC, Temmmmmo commented on auth_backend/auth_plugins/yandex.py
> +        if data.get("default_phone") and data.get("default_phone").get("number"):
ща по-другому все переделал

2023-08-13 14:09 UTC, Temmmmmo commented on auth_backend/auth_plugins/vk.py
> +            items.append({"category": "Карьера", "param": "Место работы", "value": data.get("career")["company"]})
исправил

2023-08-13 14:09 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +            cls.settings.KAFKA_USER_LOGIN_TOPIC_NAME,
исправил

2023-08-14 13:12 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth._convert_data_to_userdata_format(userinfo)
умеет, оказывается, причем даже ничего добавлять не надо

2023-08-14 13:12 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                            {"category": "Учёба", "param": "Номер зачётной книжки", "value": entrant.get("record_book")}
исправил

2023-08-14 13:12 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth._convert_data_to_userdata_format(userinfo)
исправил

2023-08-14 13:21 UTC, grigoriev-semyon requested changes

2023-08-14 13:21 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                if 3 not in faculties:
мэджик намбер в коде это антипаттерн

2023-08-14 13:21 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                else:
вынеси весь этот треш в отдельный метод

2023-08-14 13:22 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                else:
все что ниже тоже в цикле

2023-08-14 13:23 UTC, grigoriev-semyon commented on migration/script.py.mako
что за файл

2023-08-14 13:23 UTC, grigoriev-semyon commented on migration/env.py
что за файл

2023-08-14 13:23 UTC, grigoriev-semyon commented on migration/README
что за файл

2023-08-14 13:24 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth._convert_data_to_userdata_format(userinfo)
не вижу

2023-08-14 13:24 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +            cls.settings.KAFKA_USER_LOGIN_TOPIC_NAME,
не вижу

2023-08-14 14:02 UTC, Temmmmmo commented on auth_backend/auth_plugins/vk.py
> +            )
исправил

2023-08-14 14:17 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +                if 3 not in faculties:
исправил

2023-08-14 14:19 UTC, Temmmmmo commented on migration/README
исправил

2023-08-14 14:19 UTC, Temmmmmo commented on migration/env.py
исправил

2023-08-14 14:20 UTC, Temmmmmo commented on log.txt
исправил

2023-08-15 06:34 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                else:
не вижу

2023-08-15 06:34 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                    3 in faculties
мэджик намбер в коде

2023-08-15 06:34 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                    and entrant.get('faculty').get("faculty_id") != 3
мэджик намбер в коде

2023-08-15 06:35 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/vk.py
> +            )
не вижу

2023-08-15 06:36 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +            items.append({"category": "Личная информация", "param": "Отчество", "value": student.get("middle_name")})
договорились же отказаться от ифов

2023-08-15 06:37 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +                ):  # 3 - id Физического факультета
коммент лишний

2023-08-15 06:37 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +    def get_entrants(cls, data: dict[str, Any], items: list):
этот метод надо разделить еще на два метода

2023-08-15 06:38 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/vk.py
> +        logger.error(userinfo.get('city'))
что за лог

2023-08-15 06:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/vk.py
> +            items.append({"category": "Карьера", "param": "Расположение работы", "value": data.get("career")})
не очень понятный кусок кода
уж лучше добавлять сразу None тогда 
а не так по ссылке на него

2023-08-25 12:25 UTC, grigoriev-semyon requested changes

2023-08-25 12:25 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +    def get_student(cls, data: dict[str, Any], items):
нет тайп хинта

2023-08-25 12:25 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +        cls.get_entrants(data, items, student)
непонятно почему один метод что то возвращает а другой нет
я бы из обоих возвращал список который надо будет экстендить

2023-08-25 12:25 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +    def _convert_data_to_userdata_format(cls, data: dict[str, Any]) -> UserLogin:
метод не пишет id из lkmsu
а мы договорились что надо писать

2023-08-25 12:25 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth._convert_data_to_userdata_format(guser_id)
переименовать guser_id на что то более релевантное

2023-08-25 12:25 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +    def _convert_data_to_userdata_format(cls, data: dict[str, Any]) -> UserLogin:
метод не пишет id google

2023-08-25 12:25 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +    def _convert_data_to_userdata_format(cls, data: dict[str, Any]) -> UserLogin:
метод не пишет yandex id

2023-08-25 12:29 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +        cls.get_entrants(data, items, student)
норм, просто первый возвращает не совсем items, а student, но есть идея, как это красивее сделать, исправлю

2023-08-25 12:51 UTC, grigoriev-semyon commented
отправляем полное имя

2023-08-25 14:03 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +    def get_student(cls, data: dict[str, Any], items):
сделал

2023-08-25 14:03 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +        cls.get_entrants(data, items, student)
исправил

2023-08-25 14:06 UTC, Temmmmmo commented on auth_backend/auth_plugins/lkmsu.py
> +    def _convert_data_to_userdata_format(cls, data: dict[str, Any]) -> UserLogin:
исправил

2023-08-25 14:06 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        userdata = GoogleAuth._convert_data_to_userdata_format(guser_id)
исправил

2023-08-25 16:54 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +        logger.error(userinfo)
зачем лог?

2023-08-25 16:55 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        logger.error(userinfo)
А, уберу, да

2023-08-25 17:08 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +    def get_entrants(cls, data: dict[str, Any], student: dict[str, Any]) -> list[dict[str, Any]]:
data не юзается

2023-08-25 17:09 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +        return student, items
слишком сложно
передавай везде data просто

2023-08-25 17:11 UTC, grigoriev-semyon requested changes
оставил комменты

2023-08-25 17:45 UTC, Temmmmmo commented on auth_backend/auth_plugins/google.py
> +        logger.error(userinfo)
исправил

2023-08-25 21:41 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/lkmsu.py
> +            [student.get("first_name"), student.get("last_name"), student.get("middle_name")]
двараза вызов

2023-08-25 21:48 UTC, grigoriev-semyon approved these changes

2023-08-25 22:21 UTC, merged