Регистрация(почту+пароль), Вход по логину и паролю, Выход
profcomff/auth-api pull request #16
Opened 2022-11-01 16:45 UTC by semen603089

2022-11-01 17:01 UTC, dyakovri requested changes

2022-11-01 17:01 UTC, dyakovri commented on auth_backend/settings.py
> +    EMAIL: EmailStr | None
Это типа логин от почты? Если да, то это не обязательно емэил, это может быть обычная строка 
Например для логина в smpt.dyakov.space подходит просто `roman` для отправки почты с `roman@dyakov.space`

2022-11-01 17:01 UTC, dyakovri commented on migrations/versions/bd7ac9cbdfc8_init.py
> +def upgrade():
Кажется, дальше забыли включить блэк

2022-11-01 17:43 UTC, semen603089 commented on auth_backend/auth_plugins/auth_method.py
> +    @classmethod
cls же

2022-11-01 17:46 UTC, semen603089 commented on auth_backend/auth_plugins/auth_method.py
> +        self.router.add_api_route("/registration", self.registrate, methods=["POST"])
registrazione🍕🍕🍕🍕🍕🍝🍝🍝🍝🍝

2022-11-01 21:30 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +    @classmethod
Магический метод же

2022-11-01 21:31 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +
Аааа, что за пустоты?))

2022-11-01 21:31 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +    async def register(schema: EmailPost, user_id: int | None = None, token: str | None = None) -> PlainTextResponse:
![telegram-cloud-photo-size-2-5408952530228069257-y](https://user-images.githubusercontent.com/5656720/199345703-085a3b5c-c745-432f-acf1-a0cb09048fe5.jpg)
у тебя в POST запросе опять Query параметры

2022-11-01 21:32 UTC, dyakovri commented
Вмержите сюда тесты
И давайте блэк поверх
И погнали в прод

2022-11-11 12:59 UTC, dyakovri requested changes

2022-11-11 12:59 UTC, dyakovri commented on .github/workflows/tests.yml
> +        if: ${{ failure() }}
`if: always()`

2022-11-11 12:59 UTC, dyakovri commented on Makefile
> +endif
Зачем? Не переусложняй. Запиши в make db новой строкой `sleep 3 && alembic upgrade head` и не усложняй код

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +        orm_mode = True
Мне кажется, что базовая моделька должны быть одна на проект

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        query: AuthMethod = (
Это все-таки уже не `query`, а `auth_method`

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        return PlainTextResponse(status_code=201, content="Check email")
Что-то очень длинный и нечитаемый метод
Давай разделим на функции поменьше

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        confirmation_token: str = str(uuid4())
Может не uuid а просто загенерируем случайную регистронезависимую строку из букв и цифр?

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                return PlainTextResponse(status_code=200, content="Check email")
Давай во всех апишках ВСЕГДА использовать не PlainTextResponse, а JSON Response

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        salt, hashed = hashed_password.split("$")
Какой странный способ
Это так pbkdf2_hmac кодирует?

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +            return PlainTextResponse(status_code=403, content="Incorrect link")
А вообще тут лучше перекидывать на страницу ошибки на UI 
Но пока UI нет

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/routes/base.py
> +    return PlainTextResponse("Error", status_code=500)
Никаких PlainTextResponse
Вообще лучше в отдельный файл вынести

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/routes/base.py
> +app.include_router(email_router := Email().router, prefix=email_router.prefix, tags=["Email"])
Может в BaseAuthMethod добавить методы
`register_router(self, app)` и `register_all_routers(app)`?

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/routes/logout.py
> +        raise AuthFailed(error="Session expired, log in system again")
Кажется, для этого можно завести отдельную ошибку

2022-11-11 12:59 UTC, dyakovri commented on auth_backend/settings.py
> +    HOST: HttpUrl = 'http://127.0.0.1:8000'
Для чего этот хост?

2022-11-11 12:59 UTC, dyakovri commented on tests/conftest.py
> +    TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
`autocommit=False`? Тогда я не видел коммитов в коде

2022-11-11 12:59 UTC, dyakovri commented on tests/test_routes/test_login.py
> +class TestLogin:
А надо ли делить по классам, если уже делится по аналогичным файлам?

2022-11-11 12:59 UTC, dyakovri commented on tests/test_routes/test_logout.py
> +class TestLogout:
Логаут без токена
Логаут с токеном, срок годности которого вышел

2022-11-11 12:59 UTC, dyakovri commented on tests/test_routes/test_registration.py
> +class TestRegistration:
Регистрация с паролем == пустой строке
Регистрация с паролем с спецсимволами
Регистрация с почтой, в которой есть спецсимволы (`roman+msu@dyakov.space` вечно нигде не проходит)
Регистрация с почтой, отличающейся от существующей регистром букв
Регистрация на почту с пробелами

2022-11-11 12:59 UTC, dyakovri commented on utils/smtp.py
> +    smtpObj.quit()
На каждый коммит в гитхаб по письму? Вырубай

2022-11-11 12:59 UTC, dyakovri commented on utils/smtp.py
> +    smtpObj.quit()
Тебя же забанят в гугле))

2022-11-11 12:59 UTC, dyakovri commented on utils/smtp.py
> +    """
Что нового нам рассказал этот докстринг?))))))

2022-11-11 12:59 UTC, dyakovri commented on utils/smtp.py
> +    """
Что нового нам рассказал этот докстринг?))))))

2022-11-11 12:59 UTC, dyakovri commented on utils/smtp.py
> +import smtplib
Кажется, что эти тесты проверяют не ту функциональность, которую реализовывает этот проект
Типа не надо писать тесты на чужие либы

2022-11-12 10:54 UTC, grigoriev-semyon commented on utils/smtp.py
> +import smtplib
при чем здесь smtplib...

2022-11-12 10:55 UTC, grigoriev-semyon commented on utils/smtp.py
> +    smtpObj.quit()
какой коммит...

2022-11-12 11:29 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/auth_method.py
> +        orm_mode = True
Она одна вроде. Называется Base. От нее все наследуется

2022-11-12 11:36 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +            db.session.flush()
Чтобы user.id было не None

2022-11-12 11:37 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        salt, hashed = hashed_password.split("$")
Это со статьи на Хабре пример

2022-11-12 11:37 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        salt, hashed = hashed_password.split("$")
Там $ разделяет

2022-11-12 12:08 UTC, grigoriev-semyon commented on auth_backend/settings.py
> +    HOST: HttpUrl = 'http://127.0.0.1:8000'
чтобы удобнее генерит линки в сообщениях

2022-11-12 12:11 UTC, grigoriev-semyon commented on utils/smtp.py
> +import smtplib
у нас она вообще замокана

2022-11-12 12:16 UTC, grigoriev-semyon commented on auth_backend/settings.py
> +    HOST: HttpUrl = 'http://127.0.0.1:8000'
иначе надо их в коде писать а так хоть можно пробросить через ГХ

2022-11-12 12:16 UTC, grigoriev-semyon commented on auth_backend/settings.py
> +    HOST: HttpUrl = 'http://127.0.0.1:8000'
иначе надо их в коде писать а так хоть можно пробросить через ГХ

2022-11-12 19:52 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +        orm_mode = True
То есть только вот эта в методах авторизации?
Тогда у нее странное расположение, из ручек не взять. Тогда двинь ее в корень

2022-11-12 19:56 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        salt, hashed = hashed_password.split("$")
Что-то я в доке hashlib.pbkdf2_hmac этого не вижу
У тебя же хэш в отдельном поле, не?
Давай его и передашь через параметр

2022-11-12 19:56 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        salt, hashed = hashed_password.split("$")
Что-то я в доке hashlib.pbkdf2_hmac этого не вижу
У тебя же хэш в отдельном поле, не?
Давай его и передашь через параметр

2022-11-12 19:57 UTC, dyakovri commented on auth_backend/settings.py
> +    HOST: HttpUrl = 'http://127.0.0.1:8000'
Кажется, ручки сами знают, на каком их хосте запустили. Прокинь лучше оттуда

2022-11-12 19:58 UTC, dyakovri commented on utils/smtp.py
> +    smtpObj.quit()
Ну у тебя же этот тест на каждый коммит в пулл реквест запускается)

2022-11-12 19:58 UTC, dyakovri commented on utils/smtp.py
> +import smtplib
Где?

2022-11-12 19:59 UTC, dyakovri commented on utils/smtp.py
> +import smtplib
Я тогда не понимаю, что это за тесты

2022-11-13 09:10 UTC, grigoriev-semyon commented on utils/smtp.py
> +import smtplib
да че за тесты)) в этом файле нет тестов

2022-11-13 09:11 UTC, grigoriev-semyon commented on utils/smtp.py
> +import smtplib
это utils

2022-11-15 09:46 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        query: AuthMethod = (
Готово

2022-11-15 09:46 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +                return PlainTextResponse(status_code=200, content="Check email")
Готово

2022-11-15 09:47 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +            return PlainTextResponse(status_code=403, content="Incorrect link")
Готово

2022-11-15 09:47 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +                row.value = True
Готово

2022-11-15 09:47 UTC, grigoriev-semyon commented on auth_backend/models/db.py
> +    @property
Готово

2022-11-15 09:47 UTC, grigoriev-semyon commented on auth_backend/routes/logout.py
> +    return PlainTextResponse(status_code=200, content="Successful")
Готово

2022-11-15 09:47 UTC, grigoriev-semyon commented on auth_backend/routes/logout.py
> +        raise AuthFailed(error="Session expired, log in system again")
Готово

2022-11-15 09:48 UTC, grigoriev-semyon commented on tests/conftest.py
> +    TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Готово

2022-11-15 09:48 UTC, grigoriev-semyon commented on tests/test_routes/test_login.py
> +class TestLogin:
Готово

2022-11-15 09:54 UTC, grigoriev-semyon commented on utils/smtp.py
> +    """
Убрал

2022-11-15 09:54 UTC, grigoriev-semyon commented on utils/smtp.py
> +    """
Убрал

2022-11-15 13:46 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/auth_method.py
> +        orm_mode = True
Двинул

2022-11-15 13:47 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        return PlainTextResponse(status_code=201, content="Check email")
Разделил на два

2022-11-15 13:48 UTC, grigoriev-semyon commented on auth_backend/routes/base.py
> +    return PlainTextResponse("Error", status_code=500)
Лежит теперь в отдельном файле

2022-11-15 16:54 UTC, grigoriev-semyon commented on auth_backend/settings.py
> +    HOST: HttpUrl = 'http://127.0.0.1:8000'
Готово

2022-11-15 17:23 UTC, grigoriev-semyon commented on auth_backend/routes/base.py
> +app.include_router(email_router := Email().router, prefix=email_router.prefix, tags=["Email"])
Готово

2022-11-15 19:00 UTC, dyakovri commented on .github/workflows/tests.yml
> +          ENABLED_AUTH_METHODS=${{ secrets.ENABLED_AUTH_METHODS }} DB_DSN=postgresql://postgres@localhost:5432/postgres alembic upgrade head
А зачем из секретов? 
В тестах можно было и все включить просто

2022-11-15 19:00 UTC, dyakovri commented on .github/workflows/tests.yml
> +      name: Testing
Кажется, тестинг у нас не для этого

2022-11-15 19:00 UTC, dyakovri commented on Makefile
>  	alembic upgrade head
М? А зачем оба? Может просто как в шаблоне, ахах?

2022-11-15 19:02 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        return v
Но это же по умолчанию выполняется, если у тебя не `str | None` тип
Если очень хочется, сделай `constr(min_length=1)`
https://pydantic-docs.helpmanual.io/usage/types/#arguments-to-constr

2022-11-15 19:17 UTC, dyakovri requested changes

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        schema: EmailRegister, confirmation_token: str, user: User, host: str
schema – вообще не говорящее название
Больше похоже на input_user или что-то типа того

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        )
А почему оно должно идти в этой функции _register_and_send_approve_link?
Почему бы не сделать функцию _add_to_db и после нее вызвать send_confirmation_email

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                AuthMethod.value.ilike(schema.email.lower()),
Зачем lower, если ты используешь регистронезависимый `ilike`? Вообще мне ilike не очень нравится, он чисто постгресовский, не соответствует стандарту

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                return JSONResponse(status_code=200, content="Check email")
Извините, кнечно, но ваш "Check email" – это строка, а не адекватный JSON
В JSON API все ответы, обычно – это словарики
Сделай `content={status: 'success', description: 'confirmation email sent'}` или что-нибудь типа того
И во всех остальных местах аналогично

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        return JSONResponse(status_code=201, content="Check email")
Чем JSON Response выше с статусом 200 хуже JSON Response тут с статусом 201 тут?

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                return JSONResponse(status_code=200, content="Check email")
Вообще сделай какую-нибудь модельку для таких ответов, чтобы все тупые ответы были status/description или error/message или что-то типа того

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        await Email._register_and_send_approve_link(schema, confirmation_token, user, request.client.host)
И все-таки, почему это не внтри else?

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/routes/base.py
> +        app.include_router(router := method().router, prefix=router.prefix, tags=[name])
Смотрю понравились тебе эти `:=` :D

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/routes/exc_handlers.py
> +    return JSONResponse(content={"error": "500"}, status_code=500)
Ну давай не "500" а хотя бы "internal server error"

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/settings.py
> +    ENABLED_AUTH_METHODS: list[str]
Думаю, если сделать его Optional и при None включать все – решит несколько проблем с тестированием)

2022-11-15 19:17 UTC, dyakovri commented on auth_backend/settings.py
> +    ENABLED_AUTH_METHODS: list[str]
Только логику включения всех не здесь, а где включаешь)

2022-11-15 19:17 UTC, dyakovri commented on requirements.dev.txt
> +pytest-github-actions-annotate-failures
🤔

2022-11-15 19:19 UTC, dyakovri commented on Makefile
> -	alembic upgrade head
Мне все-таки больше нравится, когда есть 
```
db:
	docker run -d -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust --name db-auth_api postgres:15
	sleep 3

migrate: db
	alembic upgrade head
```
Просто потому, что это 2 атомарных действия

2022-11-15 19:21 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        db.session.add(user_session := UserSession(user_id=query.user.id, token=str(uuid4())))
Все еще `str(uuid4())`

2022-11-15 19:24 UTC, dyakovri commented on tests/test_routes/test_logout.py
> +class TestLogout:
Ты докинешь тестов?

2022-11-15 19:24 UTC, dyakovri commented on tests/test_routes/test_registration.py
> +class TestRegistration:
Ты докинешь тестов?

2022-11-15 19:27 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        salt, hashed = hashed_password.split("$")
Ну или статью скинь, я посмотрю пример
Но у меня не получилось воспроизвести

2022-11-15 19:27 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        salt, hashed = hashed_password.split("$")
пофиксил

2022-11-15 19:28 UTC, grigoriev-semyon commented on tests/test_routes/test_logout.py
> +class TestLogout:
докинул я ахаха там в старых это все

2022-11-15 19:28 UTC, grigoriev-semyon commented on tests/test_routes/test_registration.py
> +class TestRegistration:
все в старых

2022-11-15 19:31 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        db.session.add(user_session := UserSession(user_id=query.user.id, token=str(uuid4())))
убрал

2022-11-15 19:33 UTC, grigoriev-semyon commented on auth_backend/routes/base.py
> +        app.include_router(router := method().router, prefix=router.prefix, tags=[name])
ахахах да!

2022-11-15 20:35 UTC, grigoriev-semyon commented on Makefile
> -	alembic upgrade head
Готово

2022-11-15 20:46 UTC, grigoriev-semyon commented on auth_backend/settings.py
> +    ENABLED_AUTH_METHODS: list[str]
Готово

2022-11-15 21:03 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +                return JSONResponse(status_code=200, content="Check email")
Готово

2022-11-15 21:03 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        return JSONResponse(status_code=201, content="Check email")
Тем что ниже ресурс создается а выше обновляется))

2022-11-15 21:05 UTC, grigoriev-semyon commented on auth_backend/routes/exc_handlers.py
> +    return JSONResponse(content={"error": "500"}, status_code=500)
Готово

2022-11-15 21:05 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        return v
Готово

2022-11-15 21:05 UTC, grigoriev-semyon commented on Makefile
>  	alembic upgrade head
Готово

2022-11-15 21:06 UTC, grigoriev-semyon commented on .github/workflows/tests.yml
> +          ENABLED_AUTH_METHODS=${{ secrets.ENABLED_AUTH_METHODS }} DB_DSN=postgresql://postgres@localhost:5432/postgres alembic upgrade head
Готово

2022-11-15 21:32 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        schema: EmailRegister, confirmation_token: str, user: User, host: str
Готово

2022-11-15 21:33 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        await Email._register_and_send_approve_link(schema, confirmation_token, user, request.client.host)
Потому что оно не только в елсе должно отрабатывать

2022-11-16 07:39 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        return JSONResponse(status_code=201, content="Check email")
Может тогда это 2 отдельные функции, а в ручке оставить if?)

2022-11-16 07:42 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                                                                       message="Email confirmation link sent").dict())
Но это же то же самое, что просто 
```
return ResponseModel(status="Success", message="Email confirmation link sent")
```
))))))

2022-11-16 07:43 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +                                                                       message="Email confirmation link sent").dict())
А статус код?)

2022-11-16 07:44 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +            return JSONResponse(status_code=403, content=ResponseModel(status="Error", message="Incorrect link").dict())
А может лучше через `raise exception`?

2022-11-16 07:45 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        return JSONResponse(status_code=200, content=ResponseModel(status="Success", message="Email approved").dict())
`return ResponseModel(status="Success", message="Email approved")`

2022-11-16 07:46 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        pass
Это что?

2022-11-16 07:47 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        pass
Следующий ПР

2022-11-16 07:48 UTC, dyakovri commented on auth_backend/utils/smtp.py
> +            f"Subject: {subject}",
Если у тебя тут уже известен Body, может и Subject сюда?

2022-11-16 08:27 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                                                                       message="Email confirmation link sent").dict())
200 по умолчанию)

2022-11-16 08:29 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                raise SessionExpired(user_session.token)
Вот эту часть давай в какой-нибудь get_user_by_token
И это явно не единственное место, где нужна такая функция

2022-11-16 08:30 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +            db.session.add(user := User())
Давай тут все таки 
```
user = User()  # Кстати, мы тут о нем точно еще ничего не знаем?
db.session.add(user)
```

2022-11-16 08:31 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                                                                       message="Email confirmation link sent").dict())
Не, хочешь – оставь
Только .dict() все равно лишнее действие
Ну и формат не блэковский

2022-11-16 08:35 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +            db.session.add(user := User())
у него только id

2022-11-16 08:42 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +        return JSONResponse(status_code=201, content="Check email")
Ну и кажется, что 200 кода хватит
Если очень хочется поиграться с статусами, то 201 – это Created

2022-11-16 08:48 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +            db.session.add(user := User())
Готово

2022-11-16 08:56 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +                raise SessionExpired(user_session.token)
Готово

2022-11-16 08:58 UTC, grigoriev-semyon commented on auth_backend/utils/smtp.py
> +            f"Subject: {subject}",
Готово

2022-11-16 09:03 UTC, grigoriev-semyon commented on auth_backend/settings.py
> +    ENABLED_AUTH_METHODS: list[str] | None
Да, протестил 
все ок

2022-11-16 09:03 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        pass
Для изменения мыла

2022-11-16 09:52 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +                AuthMethod.value.ilike(schema.email.lower()),
Готово

2022-11-16 09:54 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +                                                                       message="Email confirmation link sent").dict())
Блэкнул

2022-11-16 09:58 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +            return JSONResponse(status_code=403, content=ResponseModel(status="Error", message="Incorrect link").dict())
starlette.HTTPException в качестве detail поддерживает только строку

2022-11-16 10:05 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        return JSONResponse(status_code=200, content=ResponseModel(status="Success", message="Email approved").dict())
Окси там где 200 теперь без джсона

2022-11-16 10:07 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +        return JSONResponse(status_code=201, content="Check email")
Теперь тут почти две отдельные функции)) Даже больше ахах

2022-11-17 19:01 UTC, merged