Backend doc ferubko
profcomff/auth-api pull request #166
Opened 2024-03-01 01:46 UTC by 89605502155

## Изменения

## Детали реализации

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-03-24 23:02 UTC, grigoriev-semyon commented
@Temmmmmo что это за ПР и почему его до сих пор не слили?

2024-03-24 23:04 UTC, grigoriev-semyon commented
@89605502155 вклюючи black на папке migrations
`black migrations`

2024-03-25 15:39 UTC, 89605502155 commented
крайний коммит ветки backend_doc_ferubko прошёл все проверки.

2024-03-26 21:52 UTC, grigoriev-semyon requested changes
очень много дублирования информации
+ надо писать в одном формате все

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +    Это get-метод.
то что это get метод понятно и без коммента об этом
там пишется же все в openapi spec

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        user_id: int: ID пользователя int.
зачем продублирован int?

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        info: Опциональный список информации для получения (группы, косвенные группы, области, методы аутентификации)  List.
info: <type_hint>: description 
советую поставить какое нибудь расширение для vscode которое генерит докстринги
надо писать все в едином формате

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +            Кроме этого он может содержать только значения из списка ["groups", "indirect_groups", "scopes", "auth_methods"].
это все давай в Literal[вот тут]

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        исключая незаданные поля и session_scope.
незапрошенные
session_scopes* typo

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        исключая незаданные поля
аналогично
убрать дублирование информации, привести все к одному виду

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +    Этот эндпоинт предназначен для обновления информации о пользователе, включая их связанные группы.
не по русски написано

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        Возвращает обновленную информацию о пользователе в виде объекта модели пользователя (UserModel).
аналогично
убрать дублирование информации, привести все к одному виду

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        None
аналогично
убрать дублирование информации, привести все к одному виду

2024-03-26 21:52 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        info: Опциональны список строк, указывающих дополнительную информацию для получения. Возможные значения:
Возможные значения надо указать в Literal[вот тут]
а ниже их можно раскрыть
это относится ко всему

2024-03-26 21:58 UTC, grigoriev-semyon commented
> крайний коммит ветки backend_doc_ferubko прошёл все проверки.

супер
поправь по ревью и можно сливать

2024-03-29 03:29 UTC, grigoriev-semyon commented
@89605502155 как будет готово не забудь тегнуть меня в ревьюверах

2024-03-30 01:57 UTC, 89605502155 commented
Вроде бы доделал

2024-03-30 02:13 UTC, grigoriev-semyon requested changes

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        info: list=Literal["groups", "indirect_groups", "scopes", "auth_methods"]: Опциональный список
`info: list[Literal[...]] | None: Опциональный список запрашиваемой информации.`

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        info: list=Literal["groups", "indirect_groups", "scopes", "auth_methods"]: Опциональный список
все что в скобках круглых удали, оно не тут должно описываться

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +            нужны Scopes: `["auth.user.read"]`.
дублирование инфы

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        исключая незаданные поля и session_scope: list[PinchedScope] | None = None .
все что после двоеточия непонятно зачем здесь

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        исключая незаданные поля и session_scope: list[PinchedScope] | None = None .
я про тайп хинт в конце

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        Метод: GET
дублирование инфы

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        info: List: Опциональны список строк, указывающих дополнительную информацию для
`info: list[Literal[...]] | None: Опциональный список запрашиваемой информации`

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +            нужны Scopes: `["auth.user.read"]`.
дублирование инфы

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +                "scopes": Получает информацию о разрешениях пользователя.
это тут не надо

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        Метод: PATCH
дублирование инфы

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +            нужны Scopes: `["auth.user.update"]`.
дублирование инфы

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        Метод: DELETE
дублирование инфы

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        current_user: UserSession: Сессия пользователя, которая НЕ может быть None. Также указано, что нужны Scopes: `["auth.user.delete"]`.
дублирование инфы

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        Метод: GET
вся секция запрос не нужна

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        Метод: PATCH
вся секция запрос не нужна

2024-03-30 02:13 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        Метод: DELETE
вся секция запрос не нужна

2024-03-30 02:14 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        исключая незаданные поля и session_scope.
не исправлено

2024-04-22 13:21 UTC, 89605502155 commented
Появилось немного времени и я исправил замечания.

2024-04-24 16:31 UTC, grigoriev-semyon commented
@89605502155 я поправил то что осталось чтобы побыстрее было
пройдись black'ом по коду пж

2024-05-04 00:40 UTC, grigoriev-semyon requested changes
Зачем в 6bcc2cf51d144ebb1163df74e86456b32585f5de откатил мои изменения?

2024-05-04 03:33 UTC, 89605502155 commented
Переделал. Вернулся к коммиту слияния и ещё раз повторил процедуру, чтобы изменения сохранились.

2024-05-04 23:20 UTC, grigoriev-semyon commented
@89605502155 не надо форс пушить в ветки если ты не понимаешь что ты делаешь
по умному надо было сделать revert коммита

вернулись не все мои изменения

2024-05-04 23:24 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        _: UserSession: Сессия пользователя, которая НЕ может быть None.
как минимум тут не вернулись мои изменения

2024-05-04 23:25 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        _: UserSession: Сессия пользователя, которая НЕ может быть None.
и тут

2024-05-04 23:25 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        current_user: UserSession: Сессия пользователя, которая НЕ может быть None.
тут тоже

2024-05-04 23:26 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        user_id: int: ID пользователя, информацию о котором нужно обновить.
и тут

2024-05-04 23:26 UTC, grigoriev-semyon commented on auth_backend/routes/user.py
> +        user_id: int: ID пользователя, информацию о котором нужно удалить.
и тут

2024-05-04 23:26 UTC, grigoriev-semyon requested changes
надо вернуть __все__ мои изменения

2024-05-04 23:28 UTC, grigoriev-semyon commented
@89605502155 просто зайди в историю в точке моего коммита, скопируй файл, примени к нему Блэк и залей

2024-05-05 12:37 UTC, grigoriev-semyon requested changes
вернулись не все мои изменения

2024-05-05 12:38 UTC, grigoriev-semyon commented
см комментарии, которые открыты до сих пор

2024-08-06 21:21 UTC, closed without merging