logginable deleting bug fix
profcomff/auth-api pull request #198
Opened 2024-08-13 11:07 UTC by Zimovchik

## Изменения

#192 
## Детали реализации

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-08-13 16:10 UTC, Temmmmmo commented on auth_backend/auth_method/oauth.py
> +            raise LastAuthMethodDelete
Ну ты замудрил немного. Тут же абстрактный класс, от которого потом наследуются другие. 
Тут достаточно проверить cls.loginable, который ты как раз добавил
Если логинейбл и при этом это последний логинейбл то рейзить ошибку

2024-08-13 16:10 UTC, Temmmmmo commented on auth_backend/auth_method/oauth.py
> +            raise LastAuthMethodDelete
И можно не делать такой огромный запрос в базу, а, например, сравнить длину списка ответа на запрос по всем логинейбл аутх методам с длиной списка ответа запроса, который выше(в 74 строке) кидался(это был запрос просто по данному методу)

2024-08-14 09:01 UTC, Zimovchik reviewed
> И можно не делать такой огромный запрос в базу, а, например, сравнить длину списка ответа на запрос по всем логинейбл аутх методам с длиной списка ответа запроса, который выше(в 74 строке) кидался(это был запрос просто по данному методу) 

Получилось даже с одним запросом поидее все сделать. Но возможно это не слишком читаемо очевидно, не знаю как лучше, но так точно быстрее

2024-08-14 20:18 UTC, Zimovchik commented on auth_backend/auth_method/oauth.py
> +                    [cls.get_name()] + [method.get_name() for method in AUTH_METHODS.values() if method.loginable]
Ну такой запрос тут сделан он сам по себе довольно абстрактен, там ниже в проверке его просто использую, но я и написал, что возможно это ге очень читаемо, и стоит сделать 2 запроса, но код будет более читаем

2024-08-14 20:25 UTC, Temmmmmo commented on auth_backend/auth_method/oauth.py
> +                    [cls.get_name()] + [method.get_name() for method in AUTH_METHODS.values() if method.loginable]
Я не совсем понимаю, что ты хочешь этим запросом получить

2024-08-14 20:26 UTC, Temmmmmo commented on auth_backend/auth_method/oauth.py
> +                    [cls.get_name()] + [method.get_name() for method in AUTH_METHODS.values() if method.loginable]
Хотя, вроде понял, а зачем туда добавлять cls.get_name() его разве там не будет в запросе?

2024-08-14 20:28 UTC, Zimovchik commented on auth_backend/auth_method/oauth.py
> +                    [cls.get_name()] + [method.get_name() for method in AUTH_METHODS.values() if method.loginable]
> Хотя, вроде понял, а зачем туда добавлять cls.get_name() его разве там не будет в запросе?

Потому что я хочу чтобы там удаляемый метод даже если он не loginable, а такое возможно

2024-08-14 20:31 UTC, Temmmmmo commented on auth_backend/auth_method/oauth.py
> +                    [cls.get_name()] + [method.get_name() for method in AUTH_METHODS.values() if method.loginable]
Типа ситуация, когда это последний метод и он не логинейбл? Ну со стороны пользователя мы такое никогда не увидим, так как доступа к удалению последнего логинейбл нет
Тут просто тогда может возникнуть проблема, когда это будет логинейбл, и тогда длина списка будет на 1 больше, и, возможно, получится удалить. Я так вижу

2024-08-14 20:37 UTC, Zimovchik commented on auth_backend/auth_method/oauth.py
> +                    [cls.get_name()] + [method.get_name() for method in AUTH_METHODS.values() if method.loginable]
Теоретически ты прав я думаю да, не подумал об этом, сейчас потестим

2024-08-14 20:59 UTC, Zimovchik commented on auth_backend/auth_method/oauth.py
> +                    [cls.get_name()] + [method.get_name() for method in AUTH_METHODS.values() if method.loginable]
> Типа ситуация, когда это последний метод и он не логинейбл? Ну со стороны пользователя мы такое никогда не увидим, так как доступа к удалению последнего логинейбл нет Тут просто тогда может возникнуть проблема, когда это будет логинейбл, и тогда длина списка будет на 1 больше, и, возможно, получится удалить. Я так вижу

Ты был прав ничего не меняется, перемудрил)

2024-08-19 16:22 UTC, Temmmmmo commented on auth_backend/auth_method/oauth.py
> +                AuthMethod.auth_method.in_([method.get_name() for method in AUTH_METHODS.values() if method.loginable]),
так зачем ты старую реализацию поменял, теперь нельзя будет удалить не логинейбл

2024-08-19 16:22 UTC, Temmmmmo commented on auth_backend/auth_method/oauth.py
> +                AuthMethod.auth_method.in_([method.get_name() for method in AUTH_METHODS.values() if method.loginable]),
так, давай еще раз разберемся
допустим у меня 3 метода, из которых 1 логинейбл, а один не логинейбл
Я пытаюсь удалить логинейбл. Тогда нужно получить все логинейбл методы мои, увидеть там список из 1 объекта, а затем сравнить со списком, который просто прокидывается через поиск по cls.get_name() в данный момент.

2024-08-21 15:47 UTC, grigoriev-semyon commented
```
➜  ~ python3.11
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class X:
...     pass
... 
>>> class Y:
...     pass
... 
>>> class Z(X, Y):
...     pass
... 
>>> issubclass(Z, X)
True
>>> issubclass(Z, Y)
True
```

2024-08-26 06:39 UTC, Zimovchik commented
> @Zimovchik
> 
> ```
> ➜  ~ python3.11
> Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> class X:
> ...     pass
> ... 
> >>> class Y:
> ...     pass
> ... 
> >>> class Z(X, Y):
> ...     pass
> ... 
> >>> issubclass(Z, X)
> True
> >>> issubclass(Z, Y)
> True
> ```



> @Zimovchik
> 
> ```
> ➜  ~ python3.11
> Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> class X:
> ...     pass
> ... 
> >>> class Y:
> ...     pass
> ... 
> >>> class Z(X, Y):
> ...     pass
> ... 
> >>> issubclass(Z, X)
> True
> >>> issubclass(Z, Y)
> True
> ```

@grigoriev-semyon я знаю что так можно делать, но не очень понимаю к чему этот тут

2024-08-26 18:23 UTC, Zimovchik commented
@Temmmmmo я поменял вообще немного логику чека, да теперь мы делаем 2 query запроса, но зато код как по мне теперь намного более читаемый и прозрачный

2024-09-03 05:45 UTC, grigoriev-semyon commented
> > @Zimovchik
> 
> > 
> 
> > ```
> 
> > ➜  ~ python3.11
> 
> > Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
> 
> > Type "help", "copyright", "credits" or "license" for more information.
> 
> > >>> class X:
> 
> > ...     pass
> 
> > ... 
> 
> > >>> class Y:
> 
> > ...     pass
> 
> > ... 
> 
> > >>> class Z(X, Y):
> 
> > ...     pass
> 
> > ... 
> 
> > >>> issubclass(Z, X)
> 
> > True
> 
> > >>> issubclass(Z, Y)
> 
> > True
> 
> > ```
> 
> 
> 
> @grigoriev-semyon я знаю что так можно делать, но не очень понимаю к чему этот тут

`issubclass(cls, LoginableMixin)`

Вот так это делается, определить можно в абстрактном классе каком нибудь

2024-09-03 05:48 UTC, Temmmmmo commented
@grigoriev-semyon 
Ты хочешь определить отдельный класс для логинейблов, от которых их наследовать?

2024-09-03 05:58 UTC, Zimovchik commented
> @grigoriev-semyon 
> Ты хочешь определить отдельный класс для логинейблов, от которых их наследовать?
> 

@Temmmmmo Я посмотрел, там уже есть такой класс, так что да нет смысла добавлять эту переменную в классы, перепишу сегодня

2024-10-13 08:58 UTC, DaymasS requested changes

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_method/oauth.py
>              method.is_deleted = True
Добавь db_session.commit() после 101 строки, так как сейчас ты вообще не внесёшь никаких изменений в бд

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_method/outer.py
> +from auth_backend.auth_method import LoginableMixin
Удалить

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/email.py
> +    loginable = True
Удалить (Привёл решение выше)

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/github.py
> +class GithubAuth(OauthMeta, LoginableMixin):
Удалить, так как issubclass() работает рекурентно (https://github.com/python/cpython/blob/4197a796ecf3a751ad7245b8d4f980d6d444b614/Objects/abstract.c#L2738)

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/google.py
> +class GoogleAuth(OauthMeta, LoginableMixin):
См. auth_backend/auth_plugins/github.py строка 31

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/keycloak.py
> +class KeycloakAuth(OauthMeta, LoginableMixin):
См. auth_backend/auth_plugins/github.py строка 31

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/lkmsu.py
> +class LkmsuAuth(OauthMeta, LoginableMixin):
См. auth_backend/auth_plugins/github.py строка 31

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/mymsu.py
> +class MyMsuAuth(YandexAuth, LoginableMixin):
См. auth_backend/auth_plugins/github.py строка 31

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/physics.py
> +class PhysicsAuth(GoogleAuth, LoginableMixin):
См. auth_backend/auth_plugins/github.py строка 31

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/telegram.py
> +class TelegramAuth(OauthMeta, LoginableMixin):
См. auth_backend/auth_plugins/github.py строка 31

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/vk.py
> +class VkAuth(OauthMeta, LoginableMixin):
См. auth_backend/auth_plugins/github.py строка 31

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_plugins/yandex.py
> +class YandexAuth(OauthMeta, LoginableMixin):
См. auth_backend/auth_plugins/github.py строка 31

2024-10-13 08:58 UTC, DaymasS commented on auth_backend/auth_method/oauth.py
> +
1. Проверка на на то, является ли наследник OauthMeta наследником LoginableMixin не имеет смысла, так как OauthMeta уже является наследником LoginableMixin => все наследники OauthMeta являются наследниками LoginableMixin
2. Предлагаю перенести эту логику в LoginableMixin, так как не все логинабл методы являются наследниками OauthMeta (Ты это исправил, захардкодив логинабл в Email). И там уже проводить проверку, является ли класс методом авторизации, например:

```python3
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        if cls.__name__.endswith('Meta') or cls.__name__.endswith('Mixin'):
            return
        cls.loginable = True
```

2024-10-13 09:33 UTC, Temmmmmo commented on auth_backend/auth_method/oauth.py
>              method.is_deleted = True
Он там ниже есть, насколько я помню

2024-10-13 09:43 UTC, DaymasS commented on auth_backend/auth_method/oauth.py
>              method.is_deleted = True
Я тестил локально, отвязывание не работает без него. Плюс на тесте, вроде, тоже не работает

2024-10-13 10:13 UTC, DaymasS commented on auth_backend/auth_method/oauth.py
> +
Артём имеет ввиду, что стоит вообще удалить переменную loginable и проверять это уже постфактум (После каждого вызова удаления аутх методов)

2024-10-18 19:36 UTC, DaymasS approved these changes

2024-10-22 16:09 UTC, Temmmmmo approved these changes

2024-10-22 16:10 UTC, merged