Reset email, password, fix tokens (fix #21, #4)
profcomff/auth-api pull request #22
Opened 2022-12-08 03:34 UTC by grigoriev-semyon

2022-12-08 03:35 UTC, grigoriev-semyon commented
+Python 3.11 support

2022-12-10 20:35 UTC, mixx3 commented on auth_backend/routes/user_session.py
> +        raise HTTPException(status_code=400, detail=ResponseModel(status="Error", message="Header missing").json())
мб это в exc_handlers?
чтоб один стиль был

2022-12-10 20:39 UTC, mixx3 commented on auth_backend/auth_plugins/auth_method.py
> +    token: constr(min_length=1)
это збс тема, видел для пароля и почты тоже поставил.

2022-12-10 20:46 UTC, mixx3 approved these changes

2022-12-10 20:46 UTC, mixx3 commented on auth_backend/auth_plugins/email.py
> +    email_validator = validator("email", allow_reuse=True)(check_email)
пароль можно хешировать на этапе валидации так же

2022-12-10 20:46 UTC, mixx3 commented on auth_backend/auth_plugins/email.py
> +    async def approve_email(token: str) -> ResponseModel:
статикметоды мб с _ делать или в функции выносить лучше?
сам не знаю как круче и удобней)

2022-12-14 19:09 UTC, dyakovri approved these changes

2022-12-14 19:09 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +    async def approve_email(token: str) -> ResponseModel:
Да, кажется, они не используются нигде извне класса. Можно запротектить

2022-12-14 19:09 UTC, dyakovri commented on auth_backend/routes/user_session.py
> +        raise HTTPException(status_code=400, detail=ResponseModel(status="Error", message="Header missing").json())
Кажется, можешь просто дефолт не прописывать и он кинет дефолтную ошибку валидации запроса

2022-12-14 19:09 UTC, dyakovri commented on auth_backend/routes/user_session.py
> +        raise HTTPException(status_code=400, detail=ResponseModel(status="Error", message="Header missing").json())
И это всех мест с хэдэром касается. А если нельзя, то Миша прав, лучше просто рэйзить ошибку

2022-12-14 19:09 UTC, dyakovri commented on auth_backend/routes/user_session.py
> +        status_code=200, content=ResponseModel(status="Success", message="Session found and exists").json()
Я думал тут вернет словарик информации о пользователе. У тебя, правда, пока только id и email, но это уже больше, чем ничего)

2022-12-14 19:09 UTC, dyakovri commented on auth_backend/settings.py
> +    FRONTEND_HOST: HttpUrl = "https://localhost.com"
localhost.com?)))

2022-12-14 19:09 UTC, dyakovri commented on auth_backend/templates/password_change_notification.html
> +<img class="header" style="width: 100%;" src=""
С картинкой разбираться не стал?

2022-12-14 19:15 UTC, dyakovri requested changes
Без комментариев :)

2022-12-27 08:42 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +    email_validator = validator("email", allow_reuse=True)(check_email)
не, валидация должна делать валидацию и ничего более

2022-12-30 21:51 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +    }
не работет(

2022-12-30 21:52 UTC, mixx3 commented on tests/test_routes/test_login.py
> +    body4 = {"email": "wrong@example.com", "password": "strong"}
```python
@pytest.mark.parametrize(
'body',
[
purest.param({
'email':...,
'password':...,
})
]
def test_smt(client, body): ...
```

2022-12-31 00:10 UTC, grigoriev-semyon commented on tests/test_routes/test_login.py
> +    body4 = {"email": "wrong@example.com", "password": "strong"}
![image](https://user-images.githubusercontent.com/33061489/210119184-399941ae-0057-4bd1-b1e3-2b039f051925.png)

2023-01-04 00:20 UTC, grigoriev-semyon commented on tests/test_routes/test_login.py
> +    body4 = {"email": "wrong@example.com", "password": "strong"}
крч я попробовал переписать на parametrize но из за особенностей тестов там код получается сложнее/больше
parametrize может удобен в случаях проще, чем когда тебе надо регнуть чела зависящего от date, остальные body не регать, одного из них еще аппрувить
Крч дичь

2023-01-04 00:22 UTC, mixx3 commented on tests/test_routes/test_login.py
> +    body4 = {"email": "wrong@example.com", "password": "strong"}
оке

2023-01-22 16:47 UTC, dyakovri approved these changes

2023-01-22 16:53 UTC, merged