Вход в приложение через аккаунт Yandex
profcomff/auth-api pull request #51
Opened 2023-03-06 13:30 UTC by Temmmmmo

Создан новый метод аутентификации yandex.py
Остальные изменения сделаны для работоспособности метода.

2023-03-06 13:38 UTC, dyakovri commented on auth_backend/auth_plugins/yandex.py
> +    YANDEX_CREDENTIALS: Json = '{}'
Давай удалим те, что не используются

2023-03-06 13:38 UTC, dyakovri commented on auth_backend/auth_plugins/yandex.py
> +    YANDEX_TEMPTOKEN: str = random_string()
Эту переменную давай перенесем в основные настройки (в тот класс, от которого наследуется этот класс). Назовем как-нибудь типа `ENCRIPTION_KEY`. Тут и в ЛК МГУ поправь на его использование, а из настроек удали

2023-03-06 20:00 UTC, grigoriev-semyon requested changes

2023-03-06 20:00 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +                        yandex_user_id = userinfo['id']
зачем такая вложенность?

2023-03-06 20:00 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/yandex.py
> +        if user is not None:
if user

2023-03-06 20:36 UTC, dyakovri commented on auth_backend/auth_plugins/mymsu.py
> +    YANDEX_CLIENT_SECRET: str | None
Этим тоже надо env задать
Чтоб мы могли из задать отличными от YandexSettings

2023-03-07 08:50 UTC, dyakovri commented on auth_backend/auth_plugins/yandex.py
> +                        yandex_user_id = userinfo['id']
Потому что так сделано в моем примере. Отказаться от контекстных менеджеров сложно

2023-03-07 08:59 UTC, dyakovri commented on auth_backend/auth_plugins/yandex.py
> +                logger.error(token_result)
logger.debug

2023-03-07 09:00 UTC, dyakovri commented on auth_backend/auth_plugins/yandex.py
> +                    yandex_user_id = userinfo['id']
Тут на 1 таб меньше надо, правда

2023-03-07 09:00 UTC, dyakovri commented on auth_backend/auth_plugins/yandex.py
> +                    yandex_user_id = userinfo['id']
111-122 строки

2023-03-07 09:02 UTC, grigoriev-semyon approved these changes

2023-03-11 16:53 UTC, dyakovri approved these changes

2023-03-11 17:05 UTC, merged