Refactoring
profcomff/auth-api pull request #82
Opened 2023-03-19 11:56 UTC by grigoriev-semyon

2023-03-19 12:46 UTC, dyakovri requested changes

2023-03-19 12:46 UTC, dyakovri commented on auth_backend/auth_plugins/db_plugins/db_aggregators.py
> +    tmp_email_confirmation_token: AuthMethod
Перенести в файл auth_plugins.email

2023-03-19 12:46 UTC, dyakovri commented on auth_backend/auth_plugins/db_plugins/db_aggregators.py
> +    user_id: AuthMethod
Аналогично перенести к плагинам авторизации

2023-03-19 12:46 UTC, dyakovri commented on auth_backend/auth_plugins/db_plugins/__init__.py
> +__all__ =["MethodMeta", "MethodsDict"]
Black

2023-03-19 21:17 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/db_plugins/db_aggregators.py
> +    user_id: AuthMethod
перенес в отдельную папку в платинах по файлам
мне надо чтобы класс назывался так же как метод
так что в файлах плагинов самих нельзя

2023-03-19 21:48 UTC, dyakovri commented on auth_backend/auth_plugins/db_plugins/db_aggregators.py
> +    user_id: AuthMethod
А зачем им называться так же? Ты же их статически добавляешь
Почему нельзя добавить префикс/суффикс к названию класса?

2023-03-21 17:02 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                     "confirmed", "confirmation_token", "tmp_email", "reset_token", "tmp_email_confirmation_token")
А зачем?

2023-03-21 17:03 UTC, dyakovri commented on auth_backend/auth_plugins/email.py
> +                     "confirmed", "confirmation_token", "tmp_email", "reset_token", "tmp_email_confirmation_token")
А еще в метаклассе это set, а тут tuple

2023-03-21 17:17 UTC, dyakovri commented on auth_backend/auth_plugins/google.py
> +        unique_google_id: AuthMethod = None
А тут нет `__fields__`?

2023-03-21 17:18 UTC, dyakovri commented on auth_backend/auth_plugins/lkmsu.py
>      class OauthResponseSchema(BaseModel):
А с остальными методами чо? ВК/Телега/ГХ/тд?

2023-03-21 17:19 UTC, dyakovri commented on auth_backend/models/db.py
> +    def auth_methods(self):
А куда тайпхинт дел?

2023-03-21 17:21 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +    class MethodMeta(metaclass=ABCMeta):
Не хватает докстринга как это использовать

2023-03-21 17:21 UTC, dyakovri reviewed
Много вопросиков, конечно, у меня

2023-03-22 08:40 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/email.py
> +                     "confirmed", "confirmation_token", "tmp_email", "reset_token", "tmp_email_confirmation_token")
чтобы не создать лишнего

2023-03-22 08:40 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/google.py
> +        unique_google_id: AuthMethod = None
добавил

2023-03-22 08:42 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/physics.py
> +    fields = PhysicsAuth
Возьмутся

2023-03-22 08:46 UTC, grigoriev-semyon commented on auth_backend/models/db.py
> +    def auth_methods(self):
импорт то ниже

2023-03-22 11:27 UTC, dyakovri reviewed
Кажется, еще тут надо 
https://github.com/profcomff/auth-api/pull/82/files#diff-c1e01421e5d70a320b0144bcdaf0d40f772e888c19b48f37d3b4d3408b6be719R231-R270

2023-03-22 11:27 UTC, dyakovri commented on auth_backend/auth_plugins/google.py
> +        __required_fields__ = __fields__ = frozenset(("unique_google_id"))
Это точно работает? Тут не тапл внутри получился

2023-03-22 11:27 UTC, dyakovri commented on auth_backend/auth_plugins/google.py
> +        __required_fields__ = __fields__ = frozenset(("unique_google_id"))
`frozenset({'_', 'd', 'e', 'g', 'i', 'l', 'n', 'o', 'q', 'u'})` ммм

2023-03-22 11:27 UTC, dyakovri commented on auth_backend/auth_plugins/github.py
> +        __required_fields__ = __fields__ = frozenset(("user_id"))
Тут не тапл внутри получился

2023-03-22 11:27 UTC, dyakovri commented on auth_backend/auth_plugins/lkmsu.py
> +        __required_fields__ = __fields__ = frozenset(("user_id"))
Тут не тапл внутри получился

2023-03-22 11:27 UTC, dyakovri commented on auth_backend/auth_plugins/methods_dict.py
> +    """
Краткого описания не хватает в 3-5 слов, чтоб было сразу понятно из подсказок IDE, что это

2023-03-22 11:27 UTC, dyakovri commented on auth_backend/auth_plugins/mymsu.py
> +        pass
А он просто не отналедуется, да?((

2023-03-22 11:27 UTC, dyakovri commented on auth_backend/auth_plugins/telegram.py
> +        __required_fields__ = __fields__ = frozenset(("user_id"))
Тут не тапл внутри получился

2023-03-22 11:27 UTC, dyakovri commented on auth_backend/auth_plugins/vk.py
> +        __required_fields__ = __fields__ = frozenset(("user_id"))
Тут не тапл внутри получился

2023-03-22 11:27 UTC, dyakovri commented on auth_backend/auth_plugins/yandex.py
> +        __required_fields__ = __fields__ = frozenset(("user_id"))
Тут не тапл внутри получился

2023-03-22 11:28 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +    class MethodMeta(metaclass=ABCMeta):
Непонятно что за `__fields__`, `__required_fields__`. Непонятно надо ли их указывать одновременно

2023-03-22 11:28 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +            db.session.commit()
Хватит пихать коммиты, flush

2023-03-22 11:29 UTC, dyakovri commented on auth_backend/auth_plugins/auth_method.py
> +            db.session.commit()
Хватит пихать коммиты, flush

2023-03-22 11:30 UTC, dyakovri commented on .github/workflows/lint.yml
> +          path: "auth_backend"
Тесты на форматирование не форматированы

2023-03-22 11:39 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/mymsu.py
> +        pass
Неа

2023-03-22 12:42 UTC, grigoriev-semyon commented
> Кажется, еще тут надо
> https://github.com/profcomff/auth-api/pull/82/files#diff-c1e01421e5d70a320b0144bcdaf0d40f772e888c19b48f37d3b4d3408b6be719R231-R270

Слишком непонятно получится тк это реализовано для абстрактного cls, там будут сплошные getattr

2023-03-22 14:18 UTC, dyakovri commented on auth_backend/auth_plugins/mymsu.py
> +    fields = MyMsuAuth
`fields = MyMsuAuth` – а он должен быть класс или таки объект класса?

2023-03-22 14:19 UTC, dyakovri commented on auth_backend/auth_plugins/mymsu.py
> +        pass
Мне не нравится, что сами классы оказываются внутри. Это заставляет оч сильно усложняет читаемость кода. Может рядом с Settings положишь классы?

2023-03-22 14:20 UTC, dyakovri commented on auth_backend/auth_plugins/telegram.py
> +        __required_fields__ = __fields__ = frozenset(("user_id",))
Давай таки в 2 строки

2023-03-22 14:20 UTC, dyakovri commented on auth_backend/models/db.py
>          """
Опять все слилось в одну строку

2023-03-22 15:17 UTC, dyakovri commented
Ну то есть `_register_auth_method` и `_delete_auth_method` можно заменить

2023-03-22 15:44 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/mymsu.py
> +    fields = MyMsuAuth
класс

2023-03-25 22:12 UTC, dyakovri approved these changes
Я бы, конечно, еще бэктков добавил
Но выглядит уже более-менее документально

2023-03-25 22:15 UTC, merged