User's sessions control
profcomff/auth-api pull request #88
Opened 2023-03-20 20:01 UTC by Temmmmmo

2023-03-20 22:52 UTC, grigoriev-semyon requested changes

2023-03-20 22:52 UTC, grigoriev-semyon commented on Makefile
> +# eYdTwyiEPNAxGriMPUwJdrdVkxEFmwfRYmVwAiksSyMeogqZqRLHhCviZlUBSnmS"
лишнее

2023-03-20 22:52 UTC, grigoriev-semyon commented on auth_backend/auth_plugins/auth_method.py
> +        return await create_session(user, scopes_list_names, db_session=db_session)
док коммент пропал

2023-03-20 22:52 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +user_session = APIRouter(prefix="", tags=["Logout"])
tags=["User Session"]

2023-03-20 22:52 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +    return user_session_control.create_session(session.user, session.scopes, db_session=db.session)
return await

2023-03-20 22:52 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +        if session.token == session.token and not delete_current:
session.token == session.token is always true

2023-03-20 22:52 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +    delete_current: bool = False,
delete_current: bool = Query(default=False)

2023-03-20 22:52 UTC, grigoriev-semyon commented on auth_backend/schemas/models.py
два одинаковых импорта

2023-03-21 09:22 UTC, dyakovri commented on Makefile
> +# eYdTwyiEPNAxGriMPUwJdrdVkxEFmwfRYmVwAiksSyMeogqZqRLHhCviZlUBSnmS"
МммММм, токены в коде :D

2023-03-21 09:24 UTC, dyakovri commented on auth_backend/routes/user_session.py
> +@user_session.post("/logout", response_model=str)
О_о Почему тут str? Поправь плз
Похоже, надо создать новую схему

2023-03-21 09:27 UTC, dyakovri commented on auth_backend/schemas/models.py
Там для решения такого есть `make format`, который кроме black запускает еще удаление лишних импортов и сортировку импортов

Что-то мы так часто отсылаем на make, что мб и стоит его установить
https://stackoverflow.com/a/57042516/20610418

2023-03-21 09:30 UTC, dyakovri commented on auth_backend/utils/user_session_control.py
> +async def _check_scopes(scopes: set[Scope], user: User) -> None:
Наверное не хватает тут докстринга. Не понятно о чем функция с первого взгляда. Можно заставить писать его Семена @grigoriev-semyon :)

2023-03-21 09:32 UTC, dyakovri commented on auth_backend/utils/user_session_control.py
> +    )
Мне кажется, что тут можно возвращать db_session, а в сессию-схему превращать в ручках. БД сессия все-таки мощнее, чем схема и нужна она чаще. Может быть в CLI ее где-нибудь применим еще, где схемы не используются

2023-03-22 17:10 UTC, Temmmmmo commented on auth_backend/utils/user_session_control.py
> +    )
Тогда придется переписывать auth-method 😶

2023-03-22 20:30 UTC, grigoriev-semyon requested changes

2023-03-22 20:30 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +async def new(session: UserSession = Depends(UnionAuth(scopes=[], allow_none=False, auto_error=True))):
create_session

2023-03-22 20:30 UTC, grigoriev-semyon commented on auth_backend/schemas/models.py
> +    message: str
ResponseModel есть уже, в модельках поищи

2023-03-22 20:31 UTC, grigoriev-semyon commented
и еще добавить новые тесты надо @Temmmmmo

2023-04-06 11:52 UTC, grigoriev-semyon requested changes

2023-04-06 11:52 UTC, grigoriev-semyon commented on auth_backend/routes/user_session.py
> +
В этой ручке у тебя сразу несколько транзакций а надо одну
Ибо пока ты идешь по циклу for какая то из сессий может протухнуть, кинет ошибку
Надо написать один запрос в базу, без циклов

2023-04-06 11:52 UTC, grigoriev-semyon commented on tests/test_routes/test_user_sessions.py
> +def test_create_session(client_auth: TestClient, dbsession: Session, user_scopes):
давай еще сюда тест если в json новой сессии передали datetime

2023-04-06 11:52 UTC, grigoriev-semyon commented on tests/test_routes/test_user_sessions.py
> +def test_get_sessions(client_auth: TestClient, dbsession: Session, user_scopes):
в конце удали одну сессию и проверь что она больше не возвращается в get all

2023-04-06 11:52 UTC, grigoriev-semyon commented on auth_backend/schemas/models.py
> +    expires: datetime | None = None
давай сюда валидатор на то что expires>now

2023-04-09 21:45 UTC, grigoriev-semyon approved these changes

2023-04-10 20:28 UTC, dyakovri reviewed
В целом, мне нравится. Логика есть, разложил по файлам тоже хорошо. Есть парочка оптимизаций, которые можно сделать, да комментариев мне не хватило, чтобы не читая функцию понимать что она делает

2023-04-10 20:28 UTC, dyakovri commented on auth_backend/routes/user_session.py
> +                token=session.token,
Целиком токены отдавать точно не надо
Давай отдавать `***1234`, ну то есть многоточие/звёздочки и последние 4 знака. Чтоб никто не украл сразу все токены

2023-04-11 13:22 UTC, grigoriev-semyon commented on tests/conftest.py
> +        dbsession.add(scope1 := Scope(name=scopes_names[i], creator_id=user_id))
for each лучше юзай)

2023-04-11 13:22 UTC, grigoriev-semyon commented on tests/conftest.py
> +    for i in range(len(scopes)):
и тут тоже for each

2023-04-11 19:53 UTC, grigoriev-semyon approved these changes

2023-04-11 19:54 UTC, merged